rateLimiter:
  STATUS:
    messageType: 'STATUS'
    maxTokens: 2
    schedule: '0 */2 * ? * *'
  NEWS:
    messageType: 'NEWS'
    maxTokens: 1
    schedule: '0 0 0 * * ?'
  MARKETING:
    messageType: 'MARKETING'
    maxTokens: 3
    schedule: '0 0 * ? * *'